### ISSUE TITLE
Timeout doesn't work as expected

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-unit#24]
When I run this test, I expect that after 5 seconds, it fails with a TimeoutException.

``` groovy
package io.vertx.ext.hawkular

import io.vertx.ext.unit.junit.Timeout
import io.vertx.groovy.ext.unit.junit.VertxUnitRunner
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

import static java.util.concurrent.TimeUnit.SECONDS

@RunWith(VertxUnitRunner.class)
class SampleTest {

  @Rule
  public Timeout timeout = new Timeout(5, SECONDS);

  @Test
  void failAsExpected() {
    while (true) {
      Thread.sleep(2000)
    }
  }
}

```

But it doesn't. It keeps running indefinitely.

If I try the same thing with the usual jUnit rule, it fails as expected:

``` groovy
package io.vertx.ext.hawkular

import org.junit.Rule
import org.junit.Test
import org.junit.rules.Timeout

class SampleTest {

  @Rule
  public Timeout timeout = new Timeout(5000);

  @Test
  void failAsExpected() {
    while (true) {
      Thread.sleep(2000)
    }
  }
}
```

Output:

```
java.lang.Exception: test timed out after 5000 milliseconds
    at java.lang.Thread.sleep(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrap.invoke(StaticMetaMethodSite.java:130)
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at io.vertx.ext.hawkular.SampleTest.failAsExpected(SampleTest.groovy:15)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

**Comment by imavroukakis** [comment]
Have you tried with the annotation as per https://github.com/vert-x3/vertx-unit/blob/master/src/main/asciidoc/java/index.adoc#timeout ?

**Comment by vietj** [comment]
timeout are possible but using the annotation as said by @imavroukakis

**Comment by olegshan** [comment]
@imavroukakis  your link doesn't work anymore, could you please tess what annotation do you mean?
