### ISSUE TITLE
TestContext.asyncAssertSuccess() don't block test in groovy

### ISSUE THREAD

**Issue by am4dr** [vert-x3/vertx-unit#40]
`io.vertx.groovy.ext.unit.TestContext.asyncAssertSuccess()` don't wait for asynchronous executions.

So, `asyncAssertSuccess()` can't replace async assertion code like [Asynchronous assertions - Vertx unit](http://vertx.io/docs/vertx-unit/groovy/#_asynchronous_assertions).

> ```
>   Async async = context.async();
>   vertx.deployVerticle("my.verticle", ar -> {
>     if (ar.succeeded()) {
>       async.complete();
>     } else {
>       context.fail(ar.cause());
>     }
>   });
> 
>   // Can be replaced by
> 
>   vertx.deployVerticle("my.verticle", context.asyncAssertSuccess());
> ```

example:

```
$ cat FailVerticle.groovy
import io.vertx.lang.groovy.GroovyVerticle

class FailVerticle extends GroovyVerticle {
    public void start(io.vertx.core.Future<Void> startFuture) {
        sleep(2000)
        startFuture.fail('fail for test')
    }
}

$ cat test.groovy
import io.vertx.groovy.ext.unit.TestContext
import io.vertx.groovy.ext.unit.TestSuite

def suite = TestSuite.create('asyncAssert_test')
suite.test('asyncAssertSuccess_fail_test') { context ->
    def s = TestSuite.create('inner suite')
    s.test('deploy_FailVerticle') { c ->
        vertx.deployVerticle('FailVerticle.groovy', c.asyncAssertSuccess())
    }
    def completion = s.run()

    // when 'deploy_FailVerticle' fail correctly, 'asyncAssertSuccess_test' pass.
    def async = context.async()
    completion.handler { ar ->
        context.assertTrue(ar.failed())
        async.complete()
    }
}
suite.run()

$ vertx test test.groovy
Begin test suite asyncAssert_test
Begin test asyncAssertSuccess_fail_test
Succeeded in deploying verticle
Begin test suite inner suite
Begin test deploy_FailVerticle
Passed deploy_FailVerticle
End test suite inner suite , run: 1, Failures: 0, Errors: 0
Failed asyncAssertSuccess_fail_test
java.lang.AssertionError: Expected true
        at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:432)
        at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:282)
        ...
End test suite asyncAssert_test , run: 1, Failures: 1, Errors: 0
```

cause (maybe):

In [TestContext#asyncAssertSuccess](https://github.com/vert-x3/vertx-unit/blob/master/src/main/groovy/io/vertx/groovy/ext/unit/TestContext.groovy#L280) (and `asyncAssertFailure`), `Async` object is not created before returning handler.

**Comment by am4dr** [comment]
Hi
This has been fixed in 3.4.0. 😃
