### ISSUE TITLE
io.vertx.core.impl.DeploymentManager SEVERE: failed to create a new resolver

### ISSUE THREAD

**Issue by mshashikumar** [vert-x3/vertx-unit#68]
Oct 17, 2019 2:34:12 PM io.vertx.core.impl.DeploymentManager
SEVERE: failed to create a new resolver
java.lang.IllegalStateException: failed to create a new resolver
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:71)
	at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:82)
	at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:804)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:82)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:304)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:190)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:186)
	at com.hmhs.saplib.verticle.BaseVerticle.lambda$start$15(BaseVerticle.java:45)
	at com.hmhs.saplib.verticle.BaseVerticle$$Lambda$52.0909F518.handle(Unknown Source)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$getConfig$2(ConfigRetrieverImpl.java:180)
	at io.vertx.config.impl.ConfigRetrieverImpl$$Lambda$39.094AC660.handle(Unknown Source)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$compute$9(ConfigRetrieverImpl.java:294)
	at io.vertx.config.impl.ConfigRetrieverImpl$$Lambda$51.093E2FB8.handle(Unknown Source)
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49)
	at io.vertx.core.impl.CompositeFutureImpl$$Lambda$50.093E28B8.handle(Unknown Source)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$null$6(ConfigRetrieverImpl.java:264)
	at io.vertx.config.impl.ConfigRetrieverImpl$$Lambda$45.094AE710.handle(Unknown Source)
	at io.vertx.config.impl.ConfigurationProvider.lambda$null$0(ConfigurationProvider.java:83)
	at io.vertx.config.impl.ConfigurationProvider$$Lambda$56.0A64DE10.handle(Unknown Source)
	at io.vertx.config.impl.spi.JsonProcessor.process(JsonProcessor.java:42)
	at io.vertx.config.impl.ConfigurationProvider.lambda$get$1(ConfigurationProvider.java:71)
	at io.vertx.config.impl.ConfigurationProvider$$Lambda$46.094AEAA8.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:284)
	at io.vertx.core.impl.ContextImpl$$Lambda$55.093E5268.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$23.09389818.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.IllegalStateException: executor not accepting a task
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:60)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1.newResolver(DnsResolverProvider.java:190)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	... 33 more

**Comment by mshashikumar** [comment]
it is fixed, by removing the code related to deploying the vertical
